### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by AlexandruGH** [andrewpeng02/transformer-translation#2]
Greetings and congrats for this beautiful work!
It's amaizing!
I would like to ask if there is any possibility to use multiple gpu's while training and inferencing?
Thanks a lot!

**Comment by andrewpeng02** [comment]
Unfortunately, because I don't have multiple GPUs I can't test this myself. However, you can fork this repo and try to add this line in train.py after instantiating the LanguageTransformer:
`model = nn.DataParallel(model)`
And then you can increase the batch size (which is the num_tokens arg). This should enable multi GPU training. Inferencing should be fast enough that you don't need to use multiple GPUs for that.
