### ISSUE TITLE
forward process for translate-sentence.py

### ISSUE THREAD

**Issue by MCLYang** [andrewpeng02/transformer-translation#6]
Hi, thank you for your project and post. You code is most understandable I have ever found in git. I am trying to understand for the forward process for `translate-sentence.py` as well.
```
    # Generate the translated sentence, feeding the model's output into its input
    translated_sentence = [fr_freq_list['[SOS]']]
    i = 0
asdasdasd        output = forward_model(model, sentence, translated_sentence).to('cuda')
        values, indices = torch.topk(output, 5)
        translated_sentence.append(int(indices[-1][0]))
```
what is the `[fr_freq_list['[SOS]']]` you put at the first place? I mean the first time pass to `forward_model`? Is it just Blank? 

Sorry I did not run your code because this is only place that confuse me. 

Thank you

_Originally posted by @MCLYang in https://github.com/andrewpeng02/transformer-translation/issues/1#issuecomment-771612221_

**Comment by andrewpeng02** [comment]
In my dictionary, I have an [SOS] token (stands for start-of-sentence) and [EOS] (end-of-sentence) tokens that are both part of the vocabulary and embedding. Because I don't know what the first word of the translated sentence is, I have to pass an [SOS] token to denote the start of the translated sentence which the model will use to predict the actual first word of the sentence. So in a way it is kind of a blank token. Did this help you?

**Comment by MCLYang** [comment]
Yes. That makes sense. you project is very helpful
